[build]
  base = "frontend/my-app"
  publish = "publish: /opt/build/repo/frontend/my-app/frontend/my-app/build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
